import React, {useCallback, useState} from 'react';
import {StyleSheet, Text, View, Dimensions, Pressable} from 'react-native';
import globalStyle from '../../assets/styles/globalStyle';
import {CheckBox} from '@rneui/themed';
import {Icon} from '@rneui/base';
import {scaleFontSize} from '../../assets/styles/scaling';
import BlueButton from '../../components/Buttons/BlueButton';
import {useDispatch, useSelector} from 'react-redux';
import {setNewPetAccessLevel} from '../../redux/slices/NewPet';
import {createPet} from '../../graphql/mutations';
import {generateClient} from 'aws-amplify/api';
import AlertBox from '../../components/AlertBox';
import AsyncStorage from '@react-native-async-storage/async-storage';

const SetAccessLevel = ({navigation}) => {
  const dispatch = useDispatch();
  const {name, birthday, deathDay, profilePic, petType, deathCause, lastWord} =
    useSelector(state => state.newPet);
  const userID = useSelector(state => state.user.cognitoUsername);
  const [checkPrivate, setPrivate] = useState(false);
  const [checkAll, setAll] = useState(true); // defaults to all
  const [isCallingAPI, setIsCallingAPI] = useState(false);
  const [petID, setPetID] = useState('');

  const onSubmit = () => {
    // save info into redux
    dispatch(setNewPetAccessLevel(checkAll));
    //upload pet info in db
    createNewPet();
    // save in async storage
    // storeDataAsyncStorage();
    return AlertBox(
      '추모공간이 성공적으로 만들어졌습니다.',
      '',
      '내 추모공간으로 이동',
      () => {
        navigation.navigate('Pets');
      },
    );
  };

  const createNewPet = async () => {
    const newPetDetails = {
      name: name,
      SK: userID,
      birthday: birthday,
      deathDay: deathDay,
      profilePic: profilePic,
      petType: petType,
      deathCause: deathCause,
      lastWord: lastWord,
      accessLevel: checkAll ? 'Public' : 'Private',
      managerID: userID,
      state: 'ACTIVE',
    };
    try {
      if (!isCallingAPI) {
        setIsCallingAPI(true);
        const client = generateClient();
        const response = await client.graphql({
          query: createPet,
          variables: {input: newPetDetails},
          authMode: 'userPool',
        });
        setPetID(response.data.createPet.id);
        console.log('response for adding new pet to db: ', response);
      }
    } catch (error) {
      console.log('error for adding new pet to db: ', error);
    } finally {
      setIsCallingAPI(false);
    }
  };

  // const storeDataAsyncStorage = async () => {
  //   if (!petID) {
  //     try {
  //       const value = {
  //         id: petID,
  //         name: name,
  //         profilePic: profilePic,
  //         birthday: birthday,
  //         deathDay: deathDay,
  //         lastWord: lastWord,
  //       };
  //       const jsonValue = JSON.stringify(value);
  //       await AsyncStorage.setItem(petID, jsonValue); // key value is petID generated by db
  //     } catch (e) {
  //       console.log('error while saving info into RN Async storage', e);
  //     }
  //   }
  // };

  return (
    <View style={[globalStyle.flex, globalStyle.backgroundWhite]}>
      <View style={styles.spacer}>
        <CheckBox
          containerStyle={styles.checkBox.container}
          right={true}
          center={true}
          textStyle={styles.checkBox.text}
          title="이 공간은 관리자가 초대한 사용자만 접근할 수 있습니다."
          checkedIcon={
            <Icon
              name="radio-button-checked"
              type="material"
              color="black"
              size={23}
              iconStyle={{marginRight: 5}}
            />
          }
          uncheckedIcon={
            <Icon
              name="radio-button-unchecked"
              type="material"
              color="grey"
              size={23}
              iconStyle={{marginRight: 5}}
            />
          }
          checked={checkPrivate}
          onPress={() => {
            setPrivate(!checkPrivate);
            setAll(!checkAll);
          }}
        />

        <CheckBox
          containerStyle={styles.checkBox.container}
          right={true}
          center={true}
          textStyle={styles.checkBox.text}
          title="전체공개 - 모든 방문자들이 추모공간을 방문하여 방명록에 글을 남길 수 있습니다."
          checkedIcon={
            <Icon
              name="radio-button-checked"
              type="material"
              color="black"
              size={23}
              iconStyle={{marginRight: 5}}
            />
          }
          uncheckedIcon={
            <Icon
              name="radio-button-unchecked"
              type="material"
              color="grey"
              size={23}
              iconStyle={{marginRight: 5}}
            />
          }
          checked={checkAll}
          onPress={() => {
            setAll(!checkAll);
            setPrivate(!checkPrivate);
          }}
        />
        <Text style={styles.direction}>
          위의 권한은 관리자가 언제든 설정에 들어가 변경할 수 있습니다.
        </Text>
        <View style={styles.blueButtonContainer}>
          <BlueButton
            title={'완료'}
            disabled={isCallingAPI}
            onPress={() => onSubmit()}
          />
        </View>
      </View>
    </View>
  );
};

export default SetAccessLevel;

const styles = StyleSheet.create({
  spacer: {
    width: '90%',
    paddingTop: Dimensions.get('window').height * 0.01,
    alignSelf: 'center',
    alignItems: 'flex-start',
  },
  checkBox: {
    container: {
      marginHorizontal: 0,
      paddingHorizontal: 0,
    },
    text: {
      fontSize: scaleFontSize(18),
      color: '#000',
      fontWeight: '400',
    },
  },
  direction: {
    fontSize: scaleFontSize(16),
    color: '#939393',
    paddingHorizontal: 10,
    paddingTop: 20,
  },
  blueButtonContainer: {
    paddingTop: Dimensions.get('window').height * 0.45,
    width: Dimensions.get('window').width * 0.27,
    alignSelf: 'center',
  },
});
